name: MLOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-east-1

    steps:

    # 1️⃣ Code Checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Install Dependencies (FIXED VERSIONS)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install \
          pandas numpy scikit-learn mlflow joblib \
          fastapi uvicorn python-multipart \
          "pathspec==0.11.2" \
          "dvc[s3]==3.30.3" \
          "s3fs==2023.6.0" \
          "aiobotocore==2.5.0"

    # 4️⃣ DVC Pull (DATA)
    - name: DVC Pull
      run: |
        dvc pull

    # 5️⃣ Train Model + MLflow Logging
    - name: Train Model
      run: |
        python src/train.py

    # 6️⃣ Metrics Output
    - name: Show Metrics
      run: |
        echo "Generated Metrics:"
        cat metrics.json || echo "metrics.json not found"
        # 7️⃣ Upload MLflow results
    - name: Upload MLflow results
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: mlruns/

    # 8️⃣ Upload Metrics file
    - name: Upload Metrics
      uses: actions/upload-artifact@v4
      with:
        name: metrics
        path: metrics.json